@startuml
skinparam sequenceArrowThickness 2
skinparam roundcorner 5
skinparam maxmessagesize 180
skinparam sequenceParticipant bold
title  CarePlan Search
participant "FHIR Client" as A #CornflowerBlue
participant "BSA Service " as B #CornflowerBlue
participant "BSA FHIR database" as C #CornflowerBlue

A -> B: GET [base]/CarePlan?Patient/ZXE24NV
B -> B: Validate
B -> C: query
C -[dashed]-> B:

B -[dashed]-> A: CarePlan Bundle Response 

@enduml
